RESTRICTED_WORDS = [
    "cure", "prescribe", "treatment plan", "definitely have", "I diagnose you", "You have"
]

ALLOWED_PHRASES = [
    "may indicate", "could be associated with", "levels are outside standard range", "consult your doctor"
]

def validate_safety(text):
    """
    Checks if the AI output contains restricted keywords.
    Returns: (is_safe: bool, flagged_words: list)
    """
    text_lower = text.lower()
    flagged = [word for word in RESTRICTED_WORDS if word in text_lower]
    return len(flagged) == 0, flagged

def sanitize_output(data):
    """
    Ensures the disclaimer is present and removes unsafe content if possible.
    """

    data['disclaimer'] = "This analysis is generated by AI and is not a medical diagnosis. Consult a qualified medical professional for proper evaluation."
    return data
